# ansible-playbook -K playbook.yml -i hosts
# Usage: ansible-playbook -K playbook.yml -i hosts --tags rust,neovim
---
- name: Setup workstation
  hosts: local
  roles:
  # set caps lock to escape: https://askubuntu.com/a/365701
  #     + Dropbox
  #     + set up obsidian with Dropbox
    - { role: prelude, tags: [prelude] }
    - { role: ghostty, tags: [ghostty] }
    - { role: rust, tags: [rust] }
    - { role: git, tags: [git] }
    - { role: keyboard, tags: [keyboard] }
    - { role: fonts, tags: [fonts] }
    - { role: starship, tags: [starship] }
    - { role: dotnet, tags: [dotnet] }
    - { role: python, tags: [python] }
    - { role: github_cli, tags: [github_cli] }
    - { role: haskell, tags: [haskell] }
    - { role: neovim, tags: [neovim] }
    - { role: ngrok, tags: [ngrok] }
    - { role: dropbox, tags: [dropbox] }
    - { role: obsidian, tags: [obsidian] }
    - { role: vscode, tags: [vscode] }
    - { role: vscode_insiders, tags: [vscode_insiders] }
    - { role: antigravity, tags: [antigravity] }
    - { role: nodejs, tags: [nodejs] }
    - { role: docker, tags: [docker] }
    # - { role: rocm, tags: [rocm] }
    # - { role: android, tags: [android] }
