---
- name: Add NodeSource apt repository
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: https://deb.nodesource.com/node_22.x
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    suites: nodistro
    components: main
    state: present
    enabled: true
  become: true

- name: Install Nodejs
  ansible.builtin.apt:
    name: nodejs
    update_cache: true
  become: true
