---
- name: Add NodeSource apt repository
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: https://deb.nodesource.com/node_22.x
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    suites: nodistro
    components: main
    architectures: ["{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"]
    state: present
    enabled: true
  become: true

- name: Install Nodejs
  ansible.builtin.apt:
    name: nodejs
    update_cache: true
  become: true

# npm global packages should be installed to ~/.npm-packages to avoid needing sudo
- name: Set npm prefix to ~/.npm-packages
  ansible.builtin.command:
    cmd: npm config set prefix "{{ lookup('ansible.builtin.env', 'HOME') }}/.npm-packages"
  changed_when: false

- name: Add ~/.npm-packages/bin to PATH
  ansible.builtin.blockinfile:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: npm"
    prepend_newline: true
    block: |
      export PATH="{{ lookup('ansible.builtin.env', 'HOME') }}/.npm-packages/bin:$PATH"
