---
- name: Create directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/Inter"
    state: directory

- name: Get latest Inter release info
  ansible.builtin.uri:
    url: https://api.github.com/repos/rsms/inter/releases/latest
    return_content: true
  register: inter_latest_release

- name: Download Inter archive
  ansible.builtin.get_url:
    url: "{{ (inter_latest_release.content | from_json).assets | selectattr('name', 'search', '^Inter-.*\\.zip$') | map(attribute='browser_download_url') | first }}"
    dest: "/tmp/Inter-latest.zip"
    mode: '0644'
  register: font_download

- name: Extract Inter TTF fonts only
  ansible.builtin.unarchive:
    src: "/tmp/Inter-latest.zip"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/Inter"
    remote_src: false
    include:
      - "Inter.ttc"
  when: font_download.changed
  notify: Update font cache
