---
- name: Create directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/Inter"
    state: directory

- name: Download Inter archive
  ansible.builtin.get_url:
    url: "https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip"
    dest: "/tmp/Inter-4.1.zip"
    mode: '0644'
  register: font_download

- name: Extract Inter
  ansible.builtin.unarchive:
    src: "/tmp/Inter-4.1.zip"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/Inter"
    remote_src: false
  when: font_download.changed
