---
- name: Create directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
    state: directory
  register: fonts_directory

- name: Download {{ item }} archive
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.tar.xz"
    dest: "/tmp/{{ item }}.tar.xz"
    mode: '0644'
  register: font_download

- name: Extract {{ item }}
  ansible.builtin.unarchive:
    src: "/tmp/{{ item }}.tar.xz.xz"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
    remote_src: false
  when: font_download.changed
  notify: Update font cache